# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaghetticheck.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spaghetticheck.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14spaghetticheck.proto\"\x15\n\x05Image\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\x0c\"@\n\tPlacement\x12\t\n\x01X\x18\x01 \x01(\x02\x12\t\n\x01Y\x18\x02 \x01(\x02\x12\r\n\x05Width\x18\x03 \x01(\x02\x12\x0e\n\x06Height\x18\x04 \x01(\x02\"^\n\tObjectHit\x12\r\n\x05\x43lass\x18\x01 \x01(\t\x12\x0f\n\x07\x43lassId\x18\x02 \x01(\x05\x12\x12\n\nConfidence\x18\x03 \x01(\x02\x12\x1d\n\tPlacement\x18\x04 \x01(\x0b\x32\n.Placement\")\n\rAnalyzedFrame\x12\x18\n\x04Hits\x18\x01 \x03(\x0b\x32\n.ObjectHit28\n\x0cImageAnalyze\x12(\n\x0c\x41nalyzeImage\x12\x06.Image\x1a\x0e.AnalyzedFrame\"\x00\x62\x06proto3'
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Data', full_name='Image.Data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=45,
)


_PLACEMENT = _descriptor.Descriptor(
  name='Placement',
  full_name='Placement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='Placement.X', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Y', full_name='Placement.Y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Width', full_name='Placement.Width', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Height', full_name='Placement.Height', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=111,
)


_OBJECTHIT = _descriptor.Descriptor(
  name='ObjectHit',
  full_name='ObjectHit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Class', full_name='ObjectHit.Class', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ClassId', full_name='ObjectHit.ClassId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Confidence', full_name='ObjectHit.Confidence', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Placement', full_name='ObjectHit.Placement', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=207,
)


_ANALYZEDFRAME = _descriptor.Descriptor(
  name='AnalyzedFrame',
  full_name='AnalyzedFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Hits', full_name='AnalyzedFrame.Hits', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=250,
)

_OBJECTHIT.fields_by_name['Placement'].message_type = _PLACEMENT
_ANALYZEDFRAME.fields_by_name['Hits'].message_type = _OBJECTHIT
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Placement'] = _PLACEMENT
DESCRIPTOR.message_types_by_name['ObjectHit'] = _OBJECTHIT
DESCRIPTOR.message_types_by_name['AnalyzedFrame'] = _ANALYZEDFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'spaghetticheck_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  })
_sym_db.RegisterMessage(Image)

Placement = _reflection.GeneratedProtocolMessageType('Placement', (_message.Message,), {
  'DESCRIPTOR' : _PLACEMENT,
  '__module__' : 'spaghetticheck_pb2'
  # @@protoc_insertion_point(class_scope:Placement)
  })
_sym_db.RegisterMessage(Placement)

ObjectHit = _reflection.GeneratedProtocolMessageType('ObjectHit', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTHIT,
  '__module__' : 'spaghetticheck_pb2'
  # @@protoc_insertion_point(class_scope:ObjectHit)
  })
_sym_db.RegisterMessage(ObjectHit)

AnalyzedFrame = _reflection.GeneratedProtocolMessageType('AnalyzedFrame', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEDFRAME,
  '__module__' : 'spaghetticheck_pb2'
  # @@protoc_insertion_point(class_scope:AnalyzedFrame)
  })
_sym_db.RegisterMessage(AnalyzedFrame)



_IMAGEANALYZE = _descriptor.ServiceDescriptor(
  name='ImageAnalyze',
  full_name='ImageAnalyze',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=252,
  serialized_end=308,
  methods=[
  _descriptor.MethodDescriptor(
    name='AnalyzeImage',
    full_name='ImageAnalyze.AnalyzeImage',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_ANALYZEDFRAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEANALYZE)

DESCRIPTOR.services_by_name['ImageAnalyze'] = _IMAGEANALYZE

# @@protoc_insertion_point(module_scope)
