# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import spaghetticheck_pb2 as spaghetticheck__pb2

class ImageAnalyzeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeImage = channel.unary_unary(
                '/ImageAnalyze/AnalyzeImage',
                request_serializer=spaghetticheck__pb2.Image.SerializeToString,
                response_deserializer=spaghetticheck__pb2.AnalyzedFrame.FromString,
                )


class ImageAnalyzeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageAnalyzeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeImage,
                    request_deserializer=spaghetticheck__pb2.Image.FromString,
                    response_serializer=spaghetticheck__pb2.AnalyzedFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageAnalyze', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageAnalyze(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageAnalyze/AnalyzeImage',
            spaghetticheck__pb2.Image.SerializeToString,
            spaghetticheck__pb2.AnalyzedFrame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
